export const PROJECTS_REQUEST = 'PROJECTS_REQUEST';
export const PROJECTS_SUCCESS = 'PROJECTS_SUCCESS';
export const PROJECTS_FAILURE = 'PROJECTS_FAILURE';

export const PROJECTS_CREATE_REQUEST = 'PROJECTS_CREATE_REQUEST';
export const PROJECTS_CREATE_SUCCESS = 'PROJECTS_CREATE_SUCCESS';
export const PROJECTS_CREATE_FAILURE = 'PROJECTS_CREATE_FAILURE';

export const PROJECTS_UPDATE_REQUEST = 'PROJECTS_UPDATE_REQUEST';
export const PROJECTS_UPDATE_SUCCESS = 'PROJECTS_UPDATE_SUCCESS';
export const PROJECTS_UPDATE_FAILURE = 'PROJECTS_UPDATE_FAILURE';

export const PROJECTS_DELETE_REQUEST = 'PROJECTS_DELETE_REQUEST';
export const PROJECTS_DELETE_SUCCESS = 'PROJECTS_DELETE_SUCCESS';
export const PROJECTS_DELETE_FAILURE = 'PROJECTS_DELETE_FAILURE';