// Project fetch
export const PROJECT_FETCH_REQUEST = 'PROJECT_REQUEST';
export const PROJECT_FETCH_SUCCESS = 'PROJECT_SUCCESS';
export const PROJECT_FETCH_FAILURE = 'PROJECT_FAILURE';

// Project update key
export const PROJECT_UPDATE_KEY_REQUEST = 'PROJECT_UPDATE_KEY_REQUEST';
export const PROJECT_UPDATE_KEY_SUCCESS = 'PROJECT_UPDATE_KEY_SUCCESS';
export const PROJECT_UPDATE_KEY_FAILURE = 'PROJECT_UPDATE_KEY_FAILURE';

// Project update
export const PROJECT_UPDATE_REQUEST = 'PROJECT_UPDATE_REQUEST';
export const PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS';
export const PROJECT_UPDATE_FAILURE = 'PROJECT_UPDATE_FAILURE';

// Server test connection
export const TEST_SERVER_CONNECTION_REQUEST = 'TEST_SERVER_CONNECTION_REQUEST';
export const TEST_SERVER_CONNECTION_SUCCESS = 'TEST_SERVER_CONNECTION_SUCCESS';
export const TEST_SERVER_CONNECTION_FAILURE = 'TEST_SERVER_CONNECTION_FAILURE';

// Server connection
export const UPDATE_SERVER_CONNECTION_STATUS = 'UPDATE_SERVER_CONNECTION_STATUS';

// Project' server remove
export const PROJECT_SERVER_REMOVE_REQUEST = 'PROJECT_SERVER_REMOVE_REQUEST';
export const PROJECT_SERVER_REMOVE_SUCCESS = 'PROJECT_SERVER_REMOVE_SUCCESS';
export const PROJECT_SERVER_REMOVE_FAILURE = 'PROJECT_SERVER_REMOVE_FAILURE';

// Project' server update
export const PROJECT_SERVER_UPDATE_REQUEST = 'PROJECT_SERVER_UPDATE_REQUEST';
export const PROJECT_SERVER_UPDATE_SUCCESS = 'PROJECT_SERVER_UPDATE_SUCCESS';
export const PROJECT_SERVER_UPDATE_FAILURE = 'PROJECT_SERVER_UPDATE_FAILURE';

// Project' server create
export const PROJECT_SERVER_CREATE_REQUEST = 'PROJECT_SERVER_CREATE_REQUEST';
export const PROJECT_SERVER_CREATE_SUCCESS = 'PROJECT_SERVER_CREATE_SUCCESS';
export const PROJECT_SERVER_CREATE_FAILURE = 'PROJECT_SERVER_CREATE_FAILURE';
