export const SERVERS_REQUEST = 'SERVERS_REQUEST';
export const SERVERS_SUCCESS = 'SERVERS_SUCCESS';
export const SERVERS_FAILURE = 'SERVERS_FAILURE';

export const SERVER_REQUEST = 'SERVER_REQUEST';
export const SERVER_SUCCESS = 'SERVER_SUCCESS';
export const SERVER_FAILURE = 'SERVER_FAILURE';

export const SERVER_UPDATE_REQUEST = 'SERVER_UPDATE_REQUEST';
export const SERVER_UPDATE_SUCCESS = 'SERVER_UPDATE_SUCCESS';
export const SERVER_UPDATE_FAILURE = 'SERVER_UPDATE_FAILURE';

export const SERVER_DELETE_REQUEST = 'SERVER_DELETE_REQUEST';
export const SERVER_DELETE_SUCCESS = 'SERVER_DELETE_SUCCESS';
export const SERVER_DELETE_FAILURE = 'SERVER_DELETE_FAILURE';

export const SERVER_CREATE_REQUEST = 'SERVER_CREATE_REQUEST';
export const SERVER_CREATE_SUCCESS = 'SERVER_CREATE_SUCCESS';
export const SERVER_CREATE_FAILURE = 'SERVER_CREATE_FAILURE';
