export const FETCH_ACCOUNT_PROVIDERS_REQUEST = 'FETCH_ACCOUNT_PROVIDERS_REQUEST';
export const FETCH_ACCOUNT_PROVIDERS_SUCCESS = 'FETCH_ACCOUNT_PROVIDERS_SUCCESS';
export const FETCH_ACCOUNT_PROVIDERS_FAILURE = 'FETCH_ACCOUNT_PROVIDERS_FAILURE';
