export const PROJECT_DEPLOYMENTS_REQUEST = 'PROJECT_DEPLOYMENTS_REQUEST';
export const PROJECT_DEPLOYMENTS_SUCCESS = 'PROJECT_DEPLOYMENTS_SUCCESS';
export const PROJECT_DEPLOYMENTS_FAILURE = 'PROJECT_DEPLOYMENTS_FAILURE';

export const PROJECT_DEPLOYMENT_CREATE_REQUEST = 'PROJECT_DEPLOYMENT_CREATE_REQUEST';
export const PROJECT_DEPLOYMENT_CREATE_SUCCESS = 'PROJECT_DEPLOYMENT_CREATE_SUCCESS';
export const PROJECT_DEPLOYMENT_CREATE_FAILURE = 'PROJECT_DEPLOYMENT_CREATE_FAILURE';

export const PROJECT_DEPLOYMENT_DEPLOYING = 'PROJECT_DEPLOYMENT_DEPLOYING';
export const PROJECT_DEPLOYMENT_DEPLOYED = 'PROJECT_DEPLOYMENT_DEPLOYED';

export const PROJECT_REDEPLOYMENT_CREATE_REQUEST = 'PROJECT_REDEPLOYMENT_CREATE_REQUEST';
export const PROJECT_REDEPLOYMENT_CREATE_SUCCESS = 'PROJECT_REDEPLOYMENT_CREATE_SUCCESS';
export const PROJECT_REDEPLOYMENT_CREATE_FAILURE = 'PROJECT_REDEPLOYMENT_CREATE_FAILURE';